=== wanclee/datashaper/DataShape.dtd
<!-- DataShape.dtd version 1.0.0 -->
<!-- Copyright (C) 2010-2012 Wan Lee, wan5332@gmail.com  -->
<!ELEMENT database ( connection ) >
<!ELEMENT connection ( #PCDATA ) >
<!ELEMENT datashape ( database, population-spec, tables-spec ) >
<!ELEMENT population-spec ( table-population+ ) >
<!ELEMENT tables-spec ( shared-sequence?, table+ ) >
<!ELEMENT shared-sequence ( #PCDATA ) >
<!ELEMENT table-population ( size, relationship?, fkey-providers? )+ >
<!ELEMENT fkey-providers ( fkey-provider*, fkey-secondary-provider*, picklist* ) >
<!ELEMENT relationship ( #PCDATA ) >
<!ELEMENT size ( #PCDATA ) >
<!ELEMENT fkey-provider ( filter?, (percent|size), random-select ) >
<!ELEMENT fkey-secondary-provider ( filter?, (percent|size), random-select ) >
<!ELEMENT picklist ( filter?, (percent|size), random-select ) >
<!ELEMENT filter ( #PCDATA ) >
<!ELEMENT percent ( #PCDATA ) >
<!ELEMENT random-select ( #PCDATA ) >
<!ELEMENT table ( local-sequence?, sql-statement, data-type, input-data, column-positions-in-query?, bindvar-column-positions? ) >
<!ELEMENT local-sequence ( #PCDATA ) >
<!ELEMENT sql-statement ( #PCDATA ) >
<!ELEMENT data-type ( #PCDATA ) >
<!ELEMENT input-data ( row+ ) >
<!ELEMENT column-positions-in-query (column+) >
<!ELEMENT bindvar-column-positions (column+) >
<!ELEMENT filter-column ( #PCDATA ) >
<!ELEMENT column ( #PCDATA ) >
<!ELEMENT row ( #PCDATA ) >

<!ATTLIST database type NMTOKEN #REQUIRED >
<!ATTLIST fkey-provider name NMTOKEN #REQUIRED >
<!ATTLIST fkey-secondary-provider name NMTOKEN #REQUIRED >
<!ATTLIST picklist name NMTOKEN #REQUIRED >
<!ATTLIST size create-new (true|false) "true" >
<!ATTLIST table name NMTOKEN #REQUIRED
			    record-id-type (numeric|alphanumeric) "numeric" >
<!ATTLIST table-population name NMTOKEN #REQUIRED >
<!ATTLIST shared-sequence name NMTOKEN #REQUIRED >
<!ATTLIST local-sequence name NMTOKEN #REQUIRED >
<!ATTLIST column name NMTOKEN #REQUIRED >

=== wanclee/datashaper/samples/postgresql/POSTGRESQLExampleUseCase1SmallScale.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">

<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Use Case: A social network site requires that 10% of its 100,000 registered users 
of age between 18 and 55 are members of 5% of the social networks of type ‘technology’, 
and 50% of its members regardless of age are members of social network of type ‘shopping’, 
and 40% of its members are members of social network of ‘cable TV’. There are 1,000,000 social networks-->

<datashape>
  <database type="POSTGRESQL">
    <connection>jdbc:postgresql://localhost:5432/actproj</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size>1000</size>
    </table-population>
    <table-population name="SN">
      <size>1000</size>
    </table-population>
    <table-population name="USR_SN_1">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <filter>AGE &gt; 18 AND AGE &lt; 55</filter>
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <fkey-provider name="SN">
          <filter>TYPE=&apos;technology&apos;</filter>
          <percent>5</percent>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
    <table-population name="USR_SN_2">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>50</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <fkey-provider name="SN">
          <filter>TYPE=&apos;shopping&apos;</filter>
	      <size>1</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
    <table-population name="USR_SN_3">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>40</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <fkey-provider name="SN">
          <filter>TYPE=&apos;cable TV&apos;</filter>
	      <size>1</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <shared-sequence name="ACTPROJ"></shared-sequence>
    <table name="USR">
      <sql-statement>INSERT INTO ACTPROJ.USR (USR_ID, EMAIL, NAME, USR_TYPE, SYS_TENANT_ID, AGE, DESCRIPTION) VALUES (?, ?, ?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, int, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;JerryDoee${ds-uuid}@yahoo.com&apos;, &apos;Mary Doee&apos;, &apos;user&apos;, &apos;123456&apos;, &apos;19&apos;, &apos;A real estate professional from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;JohnDoee${ds-uuid}@yahoo.com&apos;, &apos;John Doee&apos;, &apos;user&apos;, &apos;123456&apos;, &apos;55&apos;, &apos;A dancer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;MarshalMacc${ds-uuid}@yahoo.com&apos;, &apos;Marshal Macc&apos;, &apos;user&apos;, &apos;123456&apos;, &apos;18&apos;, &apos;A gaget geek from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;MaggieMacc${ds-uuid}@yahoo.com&apos;, &apos;Maggie Macc&apos;, &apos;user&apos;, &apos;123456&apos;, &apos;40&apos;, &apos;A swimmer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;OprahOmnily${ds-uuid}@yahoo.com&apos;, &apos;Oprah Omnily&apos;, &apos;user&apos;, &apos;123456&apos;, &apos;25&apos;, &apos;A mechanic from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;OJayOmnily${ds-uuid}@yahoo.com&apos;, &apos;OJay Omnily&apos;, &apos;user&apos;, &apos;123456&apos;, &apos;16&apos;, &apos;A high schooler from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;PeterPenneyey${ds-uuid}@yahoo.com&apos;, &apos;Peter Penneyey&apos;, &apos;user&apos;, &apos;123456&apos;, &apos;21&apos;, &apos;A singer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;PatersonPenneyey${ds-uuid}@yahoo.com&apos;, &apos;Paterson Penneyey&apos;, &apos;user&apos;, &apos;123456&apos;, &apos;35&apos;, &apos;A teacher from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;LomaLomeei${ds-uuid}@yahoo.com&apos;, &apos;Loma Lomeei&apos;, &apos;user&apos;, &apos;123456&apos;, &apos;21&apos;, &apos;A singer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;RosaLomeei${ds-uuid}@yahoo.com&apos;, &apos;Rosa Lomeei&apos;, &apos;user&apos;, &apos;123456&apos;, &apos;35&apos;, &apos;A teacher from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
      </input-data>
      <bindvar-column-positions>
        <column name="AGE">6</column>
      </bindvar-column-positions>
    </table>
    <table name="SN">
      <sql-statement>INSERT INTO ACTPROJ.SN (SN_ID, NAME, TYPE) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;Social Network${ds-current-record-id}&apos;, &apos;technology&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Social Network${ds-current-record-id}&apos;, &apos;technology&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Social Network${ds-current-record-id}&apos;, &apos;shopping&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Social Network${ds-current-record-id}&apos;, &apos;shopping&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Social Network${ds-current-record-id}&apos;, &apos;shopping&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Social Network${ds-current-record-id}&apos;, &apos;cable TV&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Social Network${ds-current-record-id}&apos;, &apos;cable TV&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Social Network${ds-current-record-id}&apos;, &apos;cable TV&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Social Network${ds-current-record-id}&apos;, &apos;cable TV&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Social Network${ds-current-record-id}&apos;, &apos;hunting&apos;</row>
      </input-data>
      <bindvar-column-positions>
        <column name="TYPE">3</column>
      </bindvar-column-positions>
    </table>
    <table name="USR_SN_1">
      <sql-statement>INSERT INTO ACTPROJ.USR_SN (USR_SN_ID, USR_ID, SN_ID) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-fkey-provider}=USR&apos;, &apos;${ds-fkey-provider}=SN&apos;</row>
      </input-data>
    </table>
    <table name="USR_SN_2">
      <sql-statement>INSERT INTO ACTPROJ.USR_SN (USR_SN_ID, USR_ID, SN_ID) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-fkey-provider}=USR&apos;, &apos;${ds-fkey-provider}=SN&apos;</row>
      </input-data>
    </table>
    <table name="USR_SN_3">
      <sql-statement>INSERT INTO ACTPROJ.USR_SN (USR_SN_ID, USR_ID, SN_ID) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-fkey-provider}=USR&apos;, &apos;${ds-fkey-provider}=SN&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/mysql/MYSQLExampleUseQuery.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">

<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Example of using a query in the data shape configuration -->
<datashape>
  <database type="MYSQL">
    <connection>jdbc:mysql://localhost:3306/actproj</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size create-new="false">by-query</size>
    </table-population>
    <table-population name="LOC">
      <size>100</size>
    </table-population>
    <table-population name="USR_LOC">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <fkey-provider name="LOC">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <table name="USR">
<!--  <sql-statement>SELECT USR_ID FROM &quot;actproj&quot;.&quot;USR&quot; where USR_TYPE=&apos;user&apos;</sql-statement>-->      
	<sql-statement>SELECT USR_ID FROM actproj.USR WHERE USR_TYPE=&apos;user&apos; order by USR_ID limit 0, 10</sql-statement>
      <data-type>empty</data-type>
      <input-data>
        <row>empty</row>
      </input-data>
    </table>
    <table name="LOC">
      <sql-statement>INSERT INTO actproj.LOC (NAME) VALUES (?)</sql-statement>
      <data-type>java.lang.String</data-type>
      <input-data>
        <row>&apos;Main Residence${ds-default-signature}&apos;</row>
      </input-data>
    </table>
    <table name="USR_LOC">
      <sql-statement>INSERT INTO actproj.USR_LOC (LOC_ID, USR_ID) VALUES (?, ?)</sql-statement>
      <data-type>long, long</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=LOC&apos;, &apos;${ds-fkey-provider}=USR&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/oracle/ORCLExampleOne2OneRelationship.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">
<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Example of 1:M relationship between a parent table and a child table -->
<datashape>
  <database type="ORCL">
    <connection>jdbc:oracle:thin:@localhost:1521:xe</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size>10</size>
    </table-population>
    <table-population name="PROFILE">
      <size>10</size>
      <relationship>1:1</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>100</percent>
          <random-select>false</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <shared-sequence name="ACTPROJ"></shared-sequence>
    <table name="USR">
      <sql-statement>INSERT INTO &quot;ACTPROJ&quot;.&quot;USR&quot; (USR_ID, EMAIL, NAME, USR_TYPE, SYS_TENANT_ID, DESCRIPTION) VALUES (?, ?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;johndoe${ds-current-record-id}@yahoo.com&apos;, &apos;John Doe ${ds-current-record-id}&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
      </input-data>
    </table>
    <table name="PROFILE">
      <sql-statement>INSERT INTO &quot;ACTPROJ&quot;.&quot;PROFILE&quot; (USR_ID, DESCRIPTION) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=USR&apos;, &apos;Always hang out at Face Bookstore ${ds-uuid}&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/oracle/ORCLExampleSeedData.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">

<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Create the seed records with user-defined ids -->

<datashape>
  <database type="ORCL">
    <connection>jdbc:oracle:thin:@localhost:1521:xe</connection>
  </database>
  <population-spec>
    <table-population name="USRTYPE">
      <size>by-input-data</size>
    </table-population>
  </population-spec>
  <tables-spec>
    <table name="USRTYPE">
      <sql-statement>INSERT INTO &quot;ACTPROJ&quot;.&quot;USRTYPE&quot; (USRTYPE_ID, NAME) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-row-id}=10001&apos;, &apos;sales-rep&apos;</row>
        <row>&apos;${ds-row-id}=10002&apos;, &apos;service-rep&apos;</row>
        <row>&apos;${ds-row-id}=10003&apos;, &apos;customer&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/postgresql/POSTGRESQLExampleDenormColumnAndPickListColumn.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">

<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Denormalized column and picklist column examples -->
<!-- Demormalized columns are columns in child table that are storing duplicate data from parent table -->
<!-- typically the parent id is stored along with other parent attribute data -->
<!-- picklist is LIST OF VALUES; picklist column stores only one selected attribute value from the picklist -->
<datashape>
  <database type="POSTGRESQL">
    <connection>jdbc:postgresql://localhost:5432/actproj</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size>100</size>
      <relationship>1:1</relationship>
      <fkey-providers>
        <picklist name="USER_TYPE_PICKLIST">
          <!-- <filter>NAME=&apos;sales-rep2&apos;</filter> -->
	      <size>1</size>
          <random-select>true</random-select>
        </picklist>
      </fkey-providers>
    </table-population>
    <table-population name="LOC">
      <size>100</size>
    </table-population>
    <table-population name="USER_TYPE_PICKLIST">
      <size create-new="false">by-query</size>
    </table-population>
    <table-population name="ADDRESS">
      <size>50</size>
    </table-population>
    <table-population name="USR_LOC">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <fkey-provider name="LOC">
          <!-- <filter>TIMEZONE=&apos;UTC+0&apos;</filter> -->
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <!-- USR_LOC can have relationship with other entities such as ADDRESS, but such relationship is not the main one -->
        <fkey-secondary-provider name="ADDRESS">
	      <size>1</size>
          <random-select>true</random-select>
        </fkey-secondary-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <shared-sequence name="ACTPROJ"></shared-sequence>
    <table name="USR">
      <sql-statement>INSERT INTO ACTPROJ.USR (USR_ID, EMAIL, NAME, USR_TYPE, SYS_TENANT_ID, DESCRIPTION) VALUES (?, ?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;johndoe533@yahoo.com&apos;, &apos;John Doe ${ds-current-record-id}&apos;, &apos;${ds-picklist}=USER_TYPE_PICKLIST.NAME&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;2johndoe533@yahoo.com&apos;, &apos;John Doe ${ds-current-record-id}&apos;, &apos;${ds-picklist}=USER_TYPE_PICKLIST.NAME&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;3johndoe533@yahoo.com&apos;, &apos;John Doe ${ds-current-record-id}&apos;, &apos;${ds-picklist}=USER_TYPE_PICKLIST.NAME&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
      </input-data>
    </table>
    <table name="LOC">
      <sql-statement>INSERT INTO ACTPROJ.LOC (LOC_ID, NAME, TIMEZONE) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;Main Residence${ds-uuid}&apos;, &apos;UTC+8&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Main Residence${ds-uuid}&apos;, &apos;UTC+0&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Main Residence${ds-uuid}&apos;, &apos;UTC-8&apos;</row>
      </input-data>
      <bindvar-column-positions>
        <column name="NAME">2</column>
        <column name="TIMEZONE">3</column>
      </bindvar-column-positions>
    </table>
    <table name="USR_LOC">
      <sql-statement>INSERT INTO ACTPROJ.USR_LOC (USR_LOC_ID, LOC_ID, USR_ID, LOC_NAME, LOC_TIMEZONE, ADDRESS_ID, ADDRESS_ZIPCODE) VALUES (?, ?, ?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal, java.math.BigDecimal, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-fkey-provider}=LOC&apos;, &apos;${ds-fkey-provider}=USR&apos;, 
        &apos;${ds-denorm-val}=LOC.NAME&apos;, &apos;${ds-denorm-val}=LOC.TIMEZONE&apos;, 
        &apos;${ds-fkey-secondary-provider}=ADDRESS&apos;, &apos;${ds-denorm-val}=ADDRESS.ZIPCODE&apos;</row>
      </input-data>
    </table>
    <table name="ADDRESS">
      <sql-statement>INSERT INTO ACTPROJ.ADDRESS (ADDRESS_ID, STREET_NUMBER, STREET_NAME, CITY, STATE, ZIPCODE, COUNTRY ) VALUES (?, ?, ?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-uuid}&apos;, &apos;Happy Days Ave&apos;, &apos;Sunnyval&apos;, &apos;California&apos;, &apos;94087&apos;, &apos;USA&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-uuid}&apos;, &apos;Happy Days Ave&apos;, &apos;Phoenix&apos;, &apos;Arizona&apos;, &apos;94087&apos;, &apos;USA&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-uuid}&apos;, &apos;Happy Days Ave&apos;, &apos;Orlando&apos;, &apos;Florida&apos;, &apos;94087&apos;, &apos;USA&apos;</row>
      </input-data>
      <bindvar-column-positions>
        <column name="ZIPCODE">6</column>
      </bindvar-column-positions>
    </table>
    <table name="USER_TYPE_PICKLIST">
      <sql-statement>SELECT USRTYPE_ID, NAME FROM ACTPROJ.USRTYPE group by USRTYPE_ID, NAME order by USRTYPE_ID offset 0 limit 10</sql-statement>
      <data-type>empty</data-type>
      <input-data>
        <row>empty</row>
      </input-data>
      <bindvar-column-positions>
        <column name="NAME">2</column>
      </bindvar-column-positions>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/mysql/MYSQLExampleOne2OneRelationship.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">
<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Example of 1:M relationship between a parent table and a child table -->

<datashape>
  <database type="MYSQL">
    <connection>jdbc:mysql://localhost:3306/actproj</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size>100</size>
    </table-population>
    <table-population name="PROFILE">
      <size>100</size>
      <relationship>1:1</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>100</percent>
          <random-select>false</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <table name="USR">
      <sql-statement>INSERT INTO actproj.USR (EMAIL, NAME, USR_TYPE, SYS_TENANT_ID, DESCRIPTION) VALUES (?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;johndoe${ds-uuid}@yahoo.com&apos;, &apos;John Doe ${ds-uuid}&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
      </input-data>
    </table>
    <table name="PROFILE">
      <sql-statement>INSERT INTO actproj.PROFILE (USR_ID, DESCRIPTION) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=USR&apos;, &apos;Always hang out at Face Bookstore ${ds-uuid}&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/db2/DB2ExampleOne2ManyRelationship.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">
<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Example of 1:M relationship between a parent table and a child table -->
<datashape>
  <database type="DB2">
    <connection>jdbc:db2://localhost:50000/actproj</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size>100</size>
    </table-population>
    <table-population name="ACTIVITY">
      <size>100</size>
      <relationship>1:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <!-- <percent>10</percent> -->
          <size>10</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <shared-sequence name="ACTPROJ"></shared-sequence>
    <table name="USR">
      <sql-statement>INSERT INTO ACTPROJ.USR (USR_ID, EMAIL, NAME, USR_TYPE, SYS_TENANT_ID, DESCRIPTION) VALUES (?, ?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;johndoe533@yahoo.com&apos;, &apos;John Doe ${ds-current-record-id}&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
      </input-data>
    </table>
    <table name="ACTIVITY">
      <sql-statement>INSERT INTO ACTPROJ.ACTIVITY (ACTIVITY_ID, USR_ID, DESCRIPTION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE) VALUES (?, ?, ?, CURRENT DATE, CURRENT DATE + 30 DAYS)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-fkey-provider}=USR&apos;, &apos;Party at ${ds-uuid} Happy Road in downtown S.J.&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/mysql/MYSQLExampleMany2ManyRelationship.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">
<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Example of M:M relationship among three entities -->

<datashape>
  <database type="MYSQL">
    <connection>jdbc:mysql://localhost:3306/actproj</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size>100</size>
    </table-population>
    <table-population name="LOC">
      <size>100</size>
    </table-population>
    <table-population name="USR_LOC">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <fkey-provider name="LOC">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <table name="USR">
      <sql-statement>INSERT INTO actproj.USR (EMAIL, SPECIAL_BLOCK, SPECIAL_BLOCK2, NAME, USR_TYPE, SYS_TENANT_ID, DESCRIPTION) VALUES (?, ?, ?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.lang.String, java.sql.Clob, java.sql.Blob, java.lang.String, java.lang.String, long, java.lang.String</data-type>
      <input-data>
        <row>&apos;johndoe533@yahoo.com&apos;, &apos;special large binary block1&apos;, &apos;special large binary block2&apos;, &apos;John Doe${ds-uuid}&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;2johndoe533@yahoo.com&apos;, &apos;special large binary block1&apos;, &apos;special large binary block2&apos;, &apos;John Doe${ds-uuid}&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;3johndoe533@yahoo.com&apos;, &apos;special large binary block1&apos;, &apos;special large binary block2&apos;, &apos;John Doe${ds-uuid}&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
      </input-data>
    </table>
    <table name="LOC">
      <sql-statement>INSERT INTO actproj.LOC (NAME) VALUES (?)</sql-statement>
      <data-type>java.lang.String</data-type>
      <input-data>
        <row>&apos;Main Residence${ds-default-signature}&apos;</row>
      </input-data>
    </table>
    <table name="USR_LOC">
      <sql-statement>INSERT INTO actproj.USR_LOC (LOC_ID, USR_ID) VALUES (?, ?)</sql-statement>
      <data-type>long, long</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=LOC&apos;, &apos;${ds-fkey-provider}=USR&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>
