=== wanclee/datashaper/DataShape.dtd
<!-- DataShape.dtd version 1.0.0 -->
<!-- Copyright (C) 2010-2012 Wan Lee, wan5332@gmail.com  -->
<!ELEMENT database ( connection ) >
<!ELEMENT connection ( #PCDATA ) >
<!ELEMENT datashape ( database, population-spec, tables-spec ) >
<!ELEMENT population-spec ( table-population+ ) >
<!ELEMENT tables-spec ( shared-sequence?, table+ ) >
<!ELEMENT shared-sequence ( #PCDATA ) >
<!ELEMENT table-population ( size, relationship?, fkey-providers? )+ >
<!ELEMENT fkey-providers ( fkey-provider*, fkey-secondary-provider*, picklist* ) >
<!ELEMENT relationship ( #PCDATA ) >
<!ELEMENT size ( #PCDATA ) >
<!ELEMENT fkey-provider ( filter?, (percent|size), random-select ) >
<!ELEMENT fkey-secondary-provider ( filter?, (percent|size), random-select ) >
<!ELEMENT picklist ( filter?, (percent|size), random-select ) >
<!ELEMENT filter ( #PCDATA ) >
<!ELEMENT percent ( #PCDATA ) >
<!ELEMENT random-select ( #PCDATA ) >
<!ELEMENT table ( local-sequence?, sql-statement, data-type, input-data, column-positions-in-query?, bindvar-column-positions? ) >
<!ELEMENT local-sequence ( #PCDATA ) >
<!ELEMENT sql-statement ( #PCDATA ) >
<!ELEMENT data-type ( #PCDATA ) >
<!ELEMENT input-data ( row+ ) >
<!ELEMENT column-positions-in-query (column+) >
<!ELEMENT bindvar-column-positions (column+) >
<!ELEMENT filter-column ( #PCDATA ) >
<!ELEMENT column ( #PCDATA ) >
<!ELEMENT row ( #PCDATA ) >

<!ATTLIST database type NMTOKEN #REQUIRED >
<!ATTLIST fkey-provider name NMTOKEN #REQUIRED >
<!ATTLIST fkey-secondary-provider name NMTOKEN #REQUIRED >
<!ATTLIST picklist name NMTOKEN #REQUIRED >
<!ATTLIST size create-new (true|false) "true" >
<!ATTLIST table name NMTOKEN #REQUIRED
			    record-id-type (numeric|alphanumeric) "numeric" >
<!ATTLIST table-population name NMTOKEN #REQUIRED >
<!ATTLIST shared-sequence name NMTOKEN #REQUIRED >
<!ATTLIST local-sequence name NMTOKEN #REQUIRED >
<!ATTLIST column name NMTOKEN #REQUIRED >

=== wanclee/datashaper/samples/mssqlserver/MSSQLServerExampleUseCase3SmallScale.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">

<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Use Case: A pool of 30,000 new opportunities captured in a Leads Management System 
on a daily basis will be distributed to 100 sales reps based on territory. -->

<datashape>
  <database type="MSSQLSERVER">
    <connection>jdbc:sqlserver://localhost:1433;DatabaseName=actproj</connection>
  </database>
  <population-spec>
    <table-population name="OPPORTUNITY">
      <size>3000</size>
    </table-population>
    <table-population name="SALESREP">
      <size create-new="false">by-query</size>
    </table-population>
    <table-population name="OPPORTUNITY_SALESREP_1">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="OPPORTUNITY">
          <filter>TERRITORY=&apos;USA&apos;</filter>
          <percent>100</percent>
          <random-select>false</random-select>
        </fkey-provider>
        <fkey-provider name="SALESREP">
          <filter>TERRITORY=&apos;USA&apos;</filter>
	      <size>1</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
    <table-population name="OPPORTUNITY_SALESREP_2">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="OPPORTUNITY">
          <filter>TERRITORY=&apos;EU&apos;</filter>
          <percent>100</percent>
          <random-select>false</random-select>
        </fkey-provider>
        <fkey-provider name="SALESREP">
          <filter>TERRITORY=&apos;EU&apos;</filter>
	      <size>1</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
    <table-population name="OPPORTUNITY_SALESREP_3">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="OPPORTUNITY">
          <filter>TERRITORY=&apos;EMEA&apos;</filter>
          <percent>100</percent>
          <random-select>false</random-select>
        </fkey-provider>
        <fkey-provider name="SALESREP">
          <filter>TERRITORY=&apos;EMEA&apos;</filter>
	      <size>1</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <table name="OPPORTUNITY">
      <sql-statement>INSERT INTO dbo.OPPTY (NAME, DEALSIZE, TERRITORY) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.lang.String, java.lang.String, java.lang.String</data-type>
      <input-data>
        <row>&apos;Opportunity${ds-uuid}&apos;, &apos;$100,000.00&apos;, &apos;USA&apos;</row>
        <row>&apos;Opportunity${ds-uuid}&apos;, &apos;$100,000.00&apos;, &apos;EU&apos;</row>
        <row>&apos;Opportunity${ds-uuid}&apos;, &apos;$1,000,000.00&apos;, &apos;EMEA&apos;</row>
        <row>&apos;Opportunity${ds-uuid}&apos;, &apos;$1,000,000.00&apos;, &apos;USA&apos;</row>
        <row>&apos;Opportunity${ds-uuid}&apos;, &apos;$500,000.00&apos;, &apos;EU&apos;</row>
        <row>&apos;Opportunity${ds-uuid}&apos;, &apos;$600,000.00&apos;, &apos;EMEA&apos;</row>
        <row>&apos;Opportunity${ds-uuid}&apos;, &apos;$10,000,000.00&apos;, &apos;USA&apos;</row>
        <row>&apos;Opportunity${ds-uuid}&apos;, &apos;$30,000,000.00&apos;, &apos;USA&apos;</row>
        <row>&apos;Opportunity${ds-uuid}&apos;, &apos;$10,000.00&apos;, &apos;EU&apos;</row>
        <row>&apos;Opportunity${ds-uuid}&apos;, &apos;$3,000,000.00&apos;, &apos;USA&apos;</row>
        <row>&apos;Opportunity${ds-uuid}&apos;, &apos;$700,000.00&apos;, &apos;EMEA&apos;</row>
      </input-data>
      <bindvar-column-positions>
        <column name="TERRITORY">3</column>
      </bindvar-column-positions>
    </table>
    <table name="OPPORTUNITY_SALESREP_1">
      <sql-statement>INSERT INTO dbo.USR_OPPTY (USR_ID, OPPTY_ID) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=SALESREP&apos;, &apos;${ds-fkey-provider}=OPPORTUNITY&apos;</row>
      </input-data>
    </table>
    <table name="OPPORTUNITY_SALESREP_2">
      <sql-statement>INSERT INTO dbo.USR_OPPTY (USR_ID, OPPTY_ID) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=SALESREP&apos;, &apos;${ds-fkey-provider}=OPPORTUNITY&apos;</row>
      </input-data>
    </table>
    <table name="OPPORTUNITY_SALESREP_3">
      <sql-statement>INSERT INTO dbo.USR_OPPTY (USR_ID, OPPTY_ID) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=SALESREP&apos;, &apos;${ds-fkey-provider}=OPPORTUNITY&apos;</row>
      </input-data>
    </table>
    <table name="SALESREP">
	  <sql-statement>SELECT USR_ID, TERRITORY FROM dbo.USR WHERE USR_TYPE=&apos;sales-rep&apos; group by USR_ID, TERRITORY order by USR_ID</sql-statement>
      <data-type>empty</data-type>
      <input-data>
        <row>empty</row>
      </input-data>
      <column-positions-in-query>
        <column name="TERRITORY">2</column>
      </column-positions-in-query>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/mysql/MYSQLExampleSeedData.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">
<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Create the seed records with user-defined ids -->

<datashape>
  <database type="MYSQL">
    <connection>jdbc:mysql://localhost:3306/ACTPROJ</connection>
  </database>
  <population-spec>
    <table-population name="USRTYPE">
      <size>by-input-data</size>
    </table-population>
  </population-spec>
  <tables-spec>
    <table name="USRTYPE">
      <sql-statement>INSERT INTO actproj.USRTYPE (USRTYPE_ID, NAME) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-row-id}=10001&apos;, &apos;sales-rep&apos;</row>
        <row>&apos;${ds-row-id}=10002&apos;, &apos;service-rep&apos;</row>
        <row>&apos;${ds-row-id}=10003&apos;, &apos;customer&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/db2/DB2ExampleMany2ManyRelationshipUseIdentityColumn.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">
<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Example of M:M relationship among three entities -->
<!-- Create the schema with actproj-db2-identity-column-option.ddl first before running this configuration file -->

<datashape>
  <database type="DB2">
    <connection>jdbc:db2://localhost:50000/actproj</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size>100</size>
    </table-population>
    <table-population name="LOC">
      <size>100</size>
    </table-population>
    <table-population name="USR_LOC">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <fkey-provider name="LOC">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <table name="USR">
      <sql-statement>INSERT INTO ACTPROJ.USR (EMAIL, NAME, USR_TYPE, SYS_TENANT_ID, DESCRIPTION) VALUES (?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;johndoe533@yahoo.com&apos;, &apos;John Doe&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;2johndoe533@yahoo.com&apos;, &apos;John Doe&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;3johndoe533@yahoo.com&apos;, &apos;John Doe&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
      </input-data>
    </table>
    <table name="LOC">
      <sql-statement>INSERT INTO ACTPROJ.LOC (NAME) VALUES (?)</sql-statement>
      <data-type>java.lang.String</data-type>
      <input-data>
        <row>&apos;Main Residence${ds-default-signature}&apos;</row>
      </input-data>
    </table>
    <table name="USR_LOC">
      <sql-statement>INSERT INTO ACTPROJ.USR_LOC (LOC_ID, USR_ID) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=LOC&apos;, &apos;${ds-fkey-provider}=USR&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/mysql/MYSQLExampleUseCase2SmallScale.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">
<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->

<!-- Use Case: An eService SAAS site requires that 50% of its 10,000,000 service request originates in U.S, 
30% Europe, and the remaining EMEA; and each service request belongs to one and only one customer 
and is associated with at least three service reps , each of them is from a different geographic time zone. -->

<datashape>
  <database type="MYSQL">
    <connection>jdbc:mysql://localhost:3306/actproj</connection>
  </database>
  <population-spec>
    <table-population name="CUSTOMER">
      <size create-new="false">by-query</size>
    </table-population>
    <table-population name="SR">
      <size>100</size>
      <relationship>1:1</relationship>
      <fkey-providers>
        <fkey-provider name="CUSTOMER">
	      <size>1</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
    <table-population name="SRP">
      <size>100</size>
    </table-population>
    <table-population name="SR_SRP_1">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="SR">
          <percent>100</percent>
          <random-select>false</random-select>
        </fkey-provider>
        <fkey-provider name="SRP">
          <filter>TIMEZONE=&apos;UTC-7&apos;</filter>
	      <size>1</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
    <table-population name="SR_SRP_2">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="SR">
          <percent>100</percent>
          <random-select>false</random-select>
        </fkey-provider>
        <fkey-provider name="SRP">
          <filter>TIMEZONE=&apos;UTC&apos;</filter>
	      <size>1</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
    <table-population name="SR_SRP_3">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="SR">
          <percent>100</percent>
          <random-select>false</random-select>
        </fkey-provider>
        <fkey-provider name="SRP">
          <filter>TIMEZONE=&apos;UTC+8&apos;</filter>
	      <size>1</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <table name="SRP">
      <sql-statement>INSERT INTO actproj.USR (EMAIL, NAME, USR_TYPE, SYS_TENANT_ID, TIMEZONE, DESCRIPTION) VALUES (?, ?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String, java.lang.String</data-type>
      <input-data>
        <row>&apos;servicerep${ds-uuid}@yahoo.com&apos;, &apos;Service Rep ${ds-uuid}&apos;, &apos;service-rep&apos;, &apos;123456&apos;, &apos;UTC-7&apos;, &apos;A dedicated service representative from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;servicerep${ds-uuid}@yahoo.com&apos;, &apos;Service Rep ${ds-uuid}&apos;, &apos;service-rep&apos;, &apos;123456&apos;, &apos;UTC&apos;, &apos;A dedicated service representative from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;servicerep${ds-uuid}@yahoo.com&apos;, &apos;Service Rep ${ds-uuid}&apos;, &apos;service-rep&apos;, &apos;123456&apos;, &apos;UTC+8&apos;, &apos;A dedicated service representative from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;servicerep${ds-uuid}@yahoo.com&apos;, &apos;Service Rep ${ds-uuid}&apos;, &apos;service-rep&apos;, &apos;123456&apos;, &apos;UTC-4&apos;, &apos;A dedicated service representative from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;servicerep${ds-uuid}@yahoo.com&apos;, &apos;Service Rep ${ds-uuid}&apos;, &apos;service-rep&apos;, &apos;123456&apos;, &apos;UTC+4&apos;, &apos;A dedicated service representative from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;servicerep${ds-uuid}@yahoo.com&apos;, &apos;Service Rep ${ds-uuid}&apos;, &apos;service-rep&apos;, &apos;123456&apos;, &apos;UTC+8&apos;, &apos;A dedicated service representative from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;servicerep${ds-uuid}@yahoo.com&apos;, &apos;Service Rep ${ds-uuid}&apos;, &apos;service-rep&apos;, &apos;123456&apos;, &apos;UTC-7&apos;, &apos;A dedicated service representative from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;servicerep${ds-uuid}@yahoo.com&apos;, &apos;Service Rep ${ds-uuid}&apos;, &apos;service-rep&apos;, &apos;123456&apos;, &apos;UTC&apos;, &apos;A dedicated service representative from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;servicerep${ds-uuid}@yahoo.com&apos;, &apos;Service Rep ${ds-uuid}&apos;, &apos;service-rep&apos;, &apos;123456&apos;, &apos;UTC-7&apos;, &apos;A dedicated service representative from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;servicerep${ds-uuid}@yahoo.com&apos;, &apos;Service Rep ${ds-uuid}&apos;, &apos;service-rep&apos;, &apos;123456&apos;, &apos;UTC&apos;, &apos;A dedicated service representative from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
      </input-data>
      <bindvar-column-positions>
        <column name="TIMEZONE">5</column>
      </bindvar-column-positions>
    </table>
    <table name="SR">
      <sql-statement>INSERT INTO actproj.SR (NAME, SOURCE, CUSTOMER_ID) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.lang.String, java.lang.String, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;Service Request${ds-uuid}&apos;, &apos;US&apos;, &apos;${ds-fkey-provider}=CUSTOMER&apos;</row>
        <row>&apos;Service Request${ds-uuid}&apos;, &apos;US&apos;, &apos;${ds-fkey-provider}=CUSTOMER&apos;</row>
        <row>&apos;Service Request${ds-uuid}&apos;, &apos;US&apos;, &apos;${ds-fkey-provider}=CUSTOMER&apos;</row>
        <row>&apos;Service Request${ds-uuid}&apos;, &apos;US&apos;, &apos;${ds-fkey-provider}=CUSTOMER&apos;</row>
        <row>&apos;Service Request${ds-uuid}&apos;, &apos;US&apos;, &apos;${ds-fkey-provider}=CUSTOMER&apos;</row>
        <row>&apos;Service Request${ds-uuid}&apos;, &apos;EU&apos;, &apos;${ds-fkey-provider}=CUSTOMER&apos;</row>
        <row>&apos;Service Request${ds-uuid}&apos;, &apos;EU&apos;, &apos;${ds-fkey-provider}=CUSTOMER&apos;</row>
        <row>&apos;Service Request${ds-uuid}&apos;, &apos;EU&apos;, &apos;${ds-fkey-provider}=CUSTOMER&apos;</row>
        <row>&apos;Service Request${ds-uuid}&apos;, &apos;EMEA&apos;, &apos;${ds-fkey-provider}=CUSTOMER&apos;</row>
        <row>&apos;Service Request${ds-uuid}&apos;, &apos;EMEA&apos;, &apos;${ds-fkey-provider}=CUSTOMER&apos;</row>
      </input-data>
    </table>
    <table name="SR_SRP_1">
      <sql-statement>INSERT INTO actproj.USR_SR (USR_ID, SR_ID) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=SRP&apos;, &apos;${ds-fkey-provider}=SR&apos;</row>
      </input-data>
    </table>
    <table name="SR_SRP_2">
      <sql-statement>INSERT INTO actproj.USR_SR (USR_ID, SR_ID) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=SRP&apos;, &apos;${ds-fkey-provider}=SR&apos;</row>
      </input-data>
    </table>
    <table name="SR_SRP_3">
      <sql-statement>INSERT INTO actproj.USR_SR (USR_ID, SR_ID) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=SRP&apos;, &apos;${ds-fkey-provider}=SR&apos;</row>
      </input-data>
    </table>
    <table name="CUSTOMER">
	  <sql-statement>SELECT USR_ID FROM actproj.USR WHERE USR_TYPE=&apos;customer&apos;  order by USR_ID limit 0, 1000000</sql-statement>
      <data-type>empty</data-type>
      <input-data>
        <row>empty</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/postgresql/POSTGRESQLExampleSimpleCreateCustomers.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">

<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Example of creating simple records such as Customers -->
<datashape>
  <database type="POSTGRESQL">
    <connection>jdbc:postgresql://localhost:5432/actproj</connection>
  </database>
  <population-spec>
    <table-population name="CUSTOMER">
      <size>1000</size>
    </table-population>
  </population-spec>
  <tables-spec>
    <shared-sequence name="ACTPROJ"></shared-sequence>
    <table name="CUSTOMER">
      <sql-statement>INSERT INTO ACTPROJ.USR (USR_ID, EMAIL, NAME, USR_TYPE, SYS_TENANT_ID, TIMEZONE, DESCRIPTION) VALUES (?, ?, ?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;customer${ds-current-record-id}@yahoo.com&apos;, &apos;Customer ${ds-current-record-id}&apos;, &apos;customer&apos;, &apos;123456&apos;, &apos;UTC-7&apos;, &apos;A loyal customer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;customer${ds-current-record-id}@yahoo.com&apos;, &apos;Customer ${ds-current-record-id}&apos;, &apos;customer&apos;, &apos;123456&apos;, &apos;UTC&apos;, &apos;A loyal customer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;customer${ds-current-record-id}@yahoo.com&apos;, &apos;Customer ${ds-current-record-id}&apos;, &apos;customer&apos;, &apos;123456&apos;, &apos;UTC+8&apos;, &apos;A loyal customer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;customer${ds-current-record-id}@yahoo.com&apos;, &apos;Customer ${ds-current-record-id}&apos;, &apos;customer&apos;, &apos;123456&apos;, &apos;UTC-4&apos;, &apos;A loyal customer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;customer${ds-current-record-id}@yahoo.com&apos;, &apos;Customer ${ds-current-record-id}&apos;, &apos;customer&apos;, &apos;123456&apos;, &apos;UTC+4&apos;, &apos;A loyal customer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;customer${ds-current-record-id}@yahoo.com&apos;, &apos;Customer ${ds-current-record-id}&apos;, &apos;customer&apos;, &apos;123456&apos;, &apos;UTC+8&apos;, &apos;A loyal customer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;customer${ds-current-record-id}@yahoo.com&apos;, &apos;Customer ${ds-current-record-id}&apos;, &apos;customer&apos;, &apos;123456&apos;, &apos;UTC-7&apos;, &apos;A loyal customer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;customer${ds-current-record-id}@yahoo.com&apos;, &apos;Customer ${ds-current-record-id}&apos;, &apos;customer&apos;, &apos;123456&apos;, &apos;UTC&apos;, &apos;A loyal customer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;customer${ds-current-record-id}@yahoo.com&apos;, &apos;Customer ${ds-current-record-id}&apos;, &apos;customer&apos;, &apos;123456&apos;, &apos;UTC-7&apos;, &apos;A loyal customer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;customer${ds-current-record-id}@yahoo.com&apos;, &apos;Customer ${ds-current-record-id}&apos;, &apos;customer&apos;, &apos;123456&apos;, &apos;UTC&apos;, &apos;A loyal customer from Sunnyvale, California. ${ds-user-signature} ${ds-current-datetime}&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>
