=== wanclee/datashaper/DataShape.dtd
<!-- DataShape.dtd version 1.0.0 -->
<!-- Copyright (C) 2010-2012 Wan Lee, wan5332@gmail.com  -->
<!ELEMENT database ( connection ) >
<!ELEMENT connection ( #PCDATA ) >
<!ELEMENT datashape ( database, population-spec, tables-spec ) >
<!ELEMENT population-spec ( table-population+ ) >
<!ELEMENT tables-spec ( shared-sequence?, table+ ) >
<!ELEMENT shared-sequence ( #PCDATA ) >
<!ELEMENT table-population ( size, relationship?, fkey-providers? )+ >
<!ELEMENT fkey-providers ( fkey-provider*, fkey-secondary-provider*, picklist* ) >
<!ELEMENT relationship ( #PCDATA ) >
<!ELEMENT size ( #PCDATA ) >
<!ELEMENT fkey-provider ( filter?, (percent|size), random-select ) >
<!ELEMENT fkey-secondary-provider ( filter?, (percent|size), random-select ) >
<!ELEMENT picklist ( filter?, (percent|size), random-select ) >
<!ELEMENT filter ( #PCDATA ) >
<!ELEMENT percent ( #PCDATA ) >
<!ELEMENT random-select ( #PCDATA ) >
<!ELEMENT table ( local-sequence?, sql-statement, data-type, input-data, column-positions-in-query?, bindvar-column-positions? ) >
<!ELEMENT local-sequence ( #PCDATA ) >
<!ELEMENT sql-statement ( #PCDATA ) >
<!ELEMENT data-type ( #PCDATA ) >
<!ELEMENT input-data ( row+ ) >
<!ELEMENT column-positions-in-query (column+) >
<!ELEMENT bindvar-column-positions (column+) >
<!ELEMENT filter-column ( #PCDATA ) >
<!ELEMENT column ( #PCDATA ) >
<!ELEMENT row ( #PCDATA ) >

<!ATTLIST database type NMTOKEN #REQUIRED >
<!ATTLIST fkey-provider name NMTOKEN #REQUIRED >
<!ATTLIST fkey-secondary-provider name NMTOKEN #REQUIRED >
<!ATTLIST picklist name NMTOKEN #REQUIRED >
<!ATTLIST size create-new (true|false) "true" >
<!ATTLIST table name NMTOKEN #REQUIRED
			    record-id-type (numeric|alphanumeric) "numeric" >
<!ATTLIST table-population name NMTOKEN #REQUIRED >
<!ATTLIST shared-sequence name NMTOKEN #REQUIRED >
<!ATTLIST local-sequence name NMTOKEN #REQUIRED >
<!ATTLIST column name NMTOKEN #REQUIRED >

=== wanclee/datashaper/samples/postgresql/POSTGRESQLExampleUseQuery.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">
<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Example of using a query in the data shape configuration -->
<datashape>
  <database type="POSTGRESQL">
    <connection>jdbc:postgresql://localhost:5432/actproj</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size create-new="false">by-query</size>
    </table-population>
    <table-population name="LOC">
      <size>100</size>
    </table-population>
    <table-population name="USR_LOC">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <fkey-provider name="LOC">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <shared-sequence name="ACTPROJ"></shared-sequence>
    <table name="USR">
<sql-statement>SELECT USR_ID FROM ACTPROJ.USR WHERE USR_TYPE=&apos;user&apos; group by USR_ID order by USR_ID offset 0 limit 10</sql-statement>
      <data-type>empty</data-type>
      <input-data>
        <row>empty</row>
      </input-data>
    </table>
    <table name="LOC">
      <sql-statement>INSERT INTO ACTPROJ.LOC (LOC_ID, NAME) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;Main Residence${ds-default-signature}&apos;</row>
      </input-data>
    </table>
    <table name="USR_LOC">
      <sql-statement>INSERT INTO ACTPROJ.USR_LOC (USR_LOC_ID, LOC_ID, USR_ID) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-fkey-provider}=LOC&apos;, &apos;${ds-fkey-provider}=USR&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/oracle/ORCLExampleAlphaNumericRowIdSimulatedWithSequenceAndTrigger.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">

<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Create records whose schema is using alphanumeric row ids -->
<!-- Create the schema with actproj-orcl-alphanumeric-rowid-implicit-sequence-with-trigger.ddl first before running this configuration file -->
<datashape>
  <database type="ORCL">
    <connection>jdbc:oracle:thin:@localhost:1521:xe</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size>10</size>
    </table-population>
    <table-population name="LOC">
      <size>10</size>
    </table-population>
    <table-population name="USR_LOC">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <fkey-provider name="LOC">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <table name="USR" record-id-type="alphanumeric">
      <sql-statement>INSERT INTO &quot;ACTPROJ&quot;.&quot;USR&quot; (EMAIL, NAME, USR_TYPE, SYS_TENANT_ID, DESCRIPTION) VALUES (?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;johndoe533@yahoo.com&apos;, &apos;John Doe&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;2johndoe533@yahoo.com&apos;, &apos;John Doe&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;3johndoe533@yahoo.com&apos;, &apos;John Doe&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
      </input-data>
    </table>
    <table name="LOC" record-id-type="alphanumeric">
      <sql-statement>INSERT INTO &quot;ACTPROJ&quot;.&quot;LOC&quot; (NAME) VALUES (?)</sql-statement>
      <data-type>java.lang.String</data-type>
      <input-data>
        <row>&apos;Main Residence${ds-default-signature}&apos;</row>
      </input-data>
    </table>
    <table name="USR_LOC" record-id-type="alphanumeric">
      <sql-statement>INSERT INTO &quot;ACTPROJ&quot;.&quot;USR_LOC&quot; (LOC_ID, USR_ID) VALUES (?, ?)</sql-statement>
      <data-type>java.lang.String, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=LOC&apos;, &apos;${ds-fkey-provider}=USR&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/mssqlserver/MSSQLServerExampleUseQuery.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">
<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Example of using a query in the data shape configuration -->
<datashape>
  <database type="MSSQLSERVER">
    <connection>jdbc:sqlserver://localhost:1433;DatabaseName=actproj</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size create-new="false">by-query</size>
    </table-population>
    <table-population name="LOC">
      <size>100</size>
    </table-population>
    <table-population name="USR_LOC">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <fkey-provider name="LOC">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <table name="USR">
	<sql-statement>SELECT USR_ID FROM dbo.USR WHERE USR_TYPE=&apos;user&apos; group by USR_ID order by USR_ID</sql-statement>
      <data-type>empty</data-type>
      <input-data>
        <row>empty</row>
      </input-data>
    </table>
    <table name="LOC">
      <sql-statement>INSERT INTO dbo.LOC (NAME) VALUES (?)</sql-statement>
      <data-type>java.lang.String</data-type>
      <input-data>
        <row>&apos;Main Residence${ds-default-signature}&apos;</row>
      </input-data>
    </table>
    <table name="USR_LOC">
      <sql-statement>INSERT INTO dbo.USR_LOC (LOC_ID, USR_ID) VALUES (?, ?)</sql-statement>
      <data-type>long, long</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=LOC&apos;, &apos;${ds-fkey-provider}=USR&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/oracle/ORCLExampleUseQuery.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">
<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Example of using a query in the data shape configuration -->
<datashape>
  <database type="ORCL">
    <connection>jdbc:oracle:thin:@localhost:1521:xe</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size create-new="false">by-query</size>
    </table-population>
    <table-population name="LOC">
      <size>10</size>
    </table-population>
    <table-population name="USR_LOC">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <fkey-provider name="LOC">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <shared-sequence name="ACTPROJ"></shared-sequence>
    <table name="USR">
<!--  <sql-statement>SELECT USR_ID FROM &quot;ACTPROJ&quot;.&quot;USR&quot; where USR_TYPE=&apos;user&apos;</sql-statement>-->      
<sql-statement>SELECT * FROM 
	(SELECT a.USR_ID, rownum R from 
		(SELECT USR_ID FROM &quot;ACTPROJ&quot;.&quot;USR&quot; WHERE USR_TYPE=&apos;user&apos; order by USR_ID) a 
		WHERE rownum &lt; 11) 
		WHERE R &gt; 0</sql-statement>
      <data-type>empty</data-type>
      <input-data>
        <row>empty</row>
      </input-data>
    </table>
    <table name="LOC">
      <sql-statement>INSERT INTO &quot;ACTPROJ&quot;.&quot;LOC&quot; (LOC_ID, NAME) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;Main Residence${ds-default-signature}&apos;</row>
      </input-data>
    </table>
    <table name="USR_LOC">
      <sql-statement>INSERT INTO &quot;ACTPROJ&quot;.&quot;USR_LOC&quot; (USR_LOC_ID, LOC_ID, USR_ID) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-fkey-provider}=LOC&apos;, &apos;${ds-fkey-provider}=USR&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/db2/DB2ExampleMany2ManyRelationship.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">
<!-- Copyright (C) 2010-2012 , Wan Lee, wan5332@gmail.com -->
<!-- Example of M:M relationship among three entities -->
<datashape>
  <database type="DB2">
    <connection>jdbc:db2://localhost:50000/actproj</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size>100</size>
    </table-population>
    <table-population name="LOC">
      <size>100</size>
    </table-population>
    <table-population name="USR_LOC">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <fkey-provider name="LOC">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <shared-sequence name="ACTPROJ"></shared-sequence>
    <table name="USR">
      <sql-statement>INSERT INTO ACTPROJ.USR (USR_ID, SPECIAL_BLOCK, SPECIAL_BLOCK2, EMAIL, NAME, USR_TYPE, SYS_TENANT_ID, DESCRIPTION) VALUES (?, ?, ?, ?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.sql.Clob, java.sql.Blob, java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;special large binary block1&apos;, &apos;special large binary block2&apos;, &apos;johndoe533@yahoo.com&apos;, &apos;John Doe ${ds-current-record-id}&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;special large binary block1&apos;, &apos;special large binary block2&apos;, &apos;2johndoe533@yahoo.com&apos;, &apos;John Doe ${ds-current-record-id}&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;special large binary block1&apos;, &apos;special large binary block2&apos;, &apos;3johndoe533@yahoo.com&apos;, &apos;John Doe ${ds-current-record-id}&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
      </input-data>
    </table>
    <table name="LOC">
      <sql-statement>INSERT INTO ACTPROJ.LOC (LOC_ID, NAME) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;Main Residence${ds-default-signature}&apos;</row>
      </input-data>
    </table>
    <table name="USR_LOC">
      <sql-statement>INSERT INTO ACTPROJ.USR_LOC (USR_LOC_ID, LOC_ID, USR_ID) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-fkey-provider}=LOC&apos;, &apos;${ds-fkey-provider}=USR&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/postgresql/POSTGRESQLExampleUseCase3SmallScale.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">

<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Use Case: A pool of 30,000 new opportunities captured in a Leads Management System 
on a daily basis will be distributed to 100 sales reps based on territory. -->

<datashape>
  <database type="POSTGRESQL">
    <connection>jdbc:postgresql://localhost:5432/actproj</connection>
  </database>
  <population-spec>
    <table-population name="OPPORTUNITY">
      <size>3000</size>
    </table-population>
    <table-population name="SALESREP">
      <size create-new="false">by-query</size>
    </table-population>
    <table-population name="OPPORTUNITY_SALESREP_1">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="OPPORTUNITY">
          <filter>TERRITORY=&apos;USA&apos;</filter>
          <percent>100</percent>
          <random-select>false</random-select>
        </fkey-provider>
        <fkey-provider name="SALESREP">
          <filter>TERRITORY=&apos;USA&apos;</filter>
	      <size>1</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
    <table-population name="OPPORTUNITY_SALESREP_2">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="OPPORTUNITY">
          <filter>TERRITORY=&apos;EU&apos;</filter>
          <percent>100</percent>
          <random-select>false</random-select>
        </fkey-provider>
        <fkey-provider name="SALESREP">
          <filter>TERRITORY=&apos;EU&apos;</filter>
	      <size>1</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
    <table-population name="OPPORTUNITY_SALESREP_3">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="OPPORTUNITY">
          <filter>TERRITORY=&apos;EMEA&apos;</filter>
          <percent>100</percent>
          <random-select>false</random-select>
        </fkey-provider>
        <fkey-provider name="SALESREP">
          <filter>TERRITORY=&apos;EMEA&apos;</filter>
	      <size>1</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <shared-sequence name="ACTPROJ"></shared-sequence>
    <table name="OPPORTUNITY">
      <sql-statement>INSERT INTO ACTPROJ.OPPTY (OPPTY_ID, NAME, DEALSIZE, TERRITORY) VALUES (?, ?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String, java.lang.String, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;Opportunity${ds-current-record-id}&apos;, &apos;$100,000.00&apos;, &apos;USA&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Opportunity${ds-current-record-id}&apos;, &apos;$100,000.00&apos;, &apos;EU&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Opportunity${ds-current-record-id}&apos;, &apos;$1,000,000.00&apos;, &apos;EMEA&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Opportunity${ds-current-record-id}&apos;, &apos;$1,000,000.00&apos;, &apos;USA&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Opportunity${ds-current-record-id}&apos;, &apos;$500,000.00&apos;, &apos;EU&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Opportunity${ds-current-record-id}&apos;, &apos;$600,000.00&apos;, &apos;EMEA&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Opportunity${ds-current-record-id}&apos;, &apos;$10,000,000.00&apos;, &apos;USA&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Opportunity${ds-current-record-id}&apos;, &apos;$30,000,000.00&apos;, &apos;USA&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Opportunity${ds-current-record-id}&apos;, &apos;$10,000.00&apos;, &apos;EU&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Opportunity${ds-current-record-id}&apos;, &apos;$3,000,000.00&apos;, &apos;USA&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;Opportunity${ds-current-record-id}&apos;, &apos;$700,000.00&apos;, &apos;EMEA&apos;</row>
      </input-data>
      <bindvar-column-positions>
        <column name="TERRITORY">4</column>
      </bindvar-column-positions>
    </table>
    <table name="OPPORTUNITY_SALESREP_1">
      <sql-statement>INSERT INTO ACTPROJ.USR_OPPTY (USR_OPPTY_ID, USR_ID, OPPTY_ID) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-fkey-provider}=SALESREP&apos;, &apos;${ds-fkey-provider}=OPPORTUNITY&apos;</row>
      </input-data>
    </table>
    <table name="OPPORTUNITY_SALESREP_2">
      <sql-statement>INSERT INTO ACTPROJ.USR_OPPTY (USR_OPPTY_ID, USR_ID, OPPTY_ID) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-fkey-provider}=SALESREP&apos;, &apos;${ds-fkey-provider}=OPPORTUNITY&apos;</row>
      </input-data>
    </table>
    <table name="OPPORTUNITY_SALESREP_3">
      <sql-statement>INSERT INTO ACTPROJ.USR_OPPTY (USR_OPPTY_ID, USR_ID, OPPTY_ID) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-fkey-provider}=SALESREP&apos;, &apos;${ds-fkey-provider}=OPPORTUNITY&apos;</row>
      </input-data>
    </table>
    <table name="SALESREP">
	  <sql-statement>SELECT USR_ID, TERRITORY FROM ACTPROJ.USR WHERE USR_TYPE=&apos;sales-rep&apos; group by USR_ID, TERRITORY order by USR_ID, TERRITORY offset 0 limit 1000000</sql-statement>
      <data-type>empty</data-type>
      <input-data>
        <row>empty</row>
      </input-data>
      <column-positions-in-query>
        <column name="TERRITORY">2</column>
      </column-positions-in-query>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/mssqlserver/MSSQLServerExampleOne2ManyRelationship.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">

<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<!-- Example of 1:M relationship between a parent table and a child table -->
<datashape>
  <database type="MSSQLSERVER">
    <connection>jdbc:sqlserver://localhost:1433;DatabaseName=actproj</connection>
  </database>
<population-spec>
    <table-population name="USR">
      <size>100</size>
    </table-population>
    <table-population name="ACTIVITY">
      <size>100</size>
      <relationship>1:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <!-- <percent>10</percent> -->
          <size>10</size>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <table name="USR">
      <sql-statement>INSERT INTO dbo.USR (EMAIL, NAME, USR_TYPE, SYS_TENANT_ID, DESCRIPTION) VALUES (?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;johndoe533@yahoo.com&apos;, &apos;John Doe ${ds-uuid}&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
      </input-data>
    </table>
    <table name="ACTIVITY">
      <sql-statement>INSERT INTO dbo.ACTIVITY (USR_ID, DESCRIPTION, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE) VALUES (?, ?, GETDATE(), DATEADD(day, 30, GETDATE()))</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-fkey-provider}=USR&apos;, &apos;Party at ${ds-uuid} Happy Road in downtown S.J.&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>

=== wanclee/datashaper/samples/postgresql/POSTGRESQLExampleMany2ManyRelationshipUseImplicitSequence.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE datashape SYSTEM "DataShape.dtd">

<!-- Copyright (C) 2010-2012, Wan Lee, wan5332@gmail.com -->
<datashape>
  <database type="POSTGRESQL">
    <connection>jdbc:postgresql://localhost:5432/actproj</connection>
  </database>
  <population-spec>
    <table-population name="USR">
      <size>100</size>
    </table-population>
    <table-population name="LOC">
      <size>100</size>
    </table-population>
    <table-population name="USR_LOC">
      <size>by-derivation</size>
      <relationship>M:M</relationship>
      <fkey-providers>
        <fkey-provider name="USR">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
        <fkey-provider name="LOC">
          <percent>10</percent>
          <random-select>true</random-select>
        </fkey-provider>
      </fkey-providers>
    </table-population>
  </population-spec>
  <tables-spec>
    <table name="USR">
      <local-sequence name="USR_USR_ID_SEQ"></local-sequence>
      <sql-statement>INSERT INTO ACTPROJ.USR (USR_ID, EMAIL, NAME, USR_TYPE, SYS_TENANT_ID, DESCRIPTION) VALUES (?, ?, ?, ?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;johndoe533@yahoo.com&apos;, &apos;John Doe&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;2johndoe533@yahoo.com&apos;, &apos;John Doe&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
        <row>&apos;${ds-nextval}&apos;, &apos;3johndoe533@yahoo.com&apos;, &apos;John Doe&apos;, &apos;user&apos;, &apos;0&apos;, &apos;A software developer from Sunnyvale, California. ${ds-current-date} ${ds-default-signature} ${ds-current-datetime}&apos;</row>
      </input-data>
    </table>
    <table name="LOC">
      <local-sequence name="LOC_LOC_ID_SEQ"></local-sequence>
      <sql-statement>INSERT INTO ACTPROJ.LOC (LOC_ID, NAME) VALUES (?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.lang.String</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;Main Residence${ds-default-signature}&apos;</row>
      </input-data>
    </table>
    <table name="USR_LOC">
      <local-sequence name="USR_LOC_USR_LOC_ID_SEQ"></local-sequence>
      <sql-statement>INSERT INTO ACTPROJ.USR_LOC (USR_LOC_ID, LOC_ID, USR_ID) VALUES (?, ?, ?)</sql-statement>
      <data-type>java.math.BigDecimal, java.math.BigDecimal, java.math.BigDecimal</data-type>
      <input-data>
        <row>&apos;${ds-nextval}&apos;, &apos;${ds-fkey-provider}=LOC&apos;, &apos;${ds-fkey-provider}=USR&apos;</row>
      </input-data>
    </table>
  </tables-spec>
</datashape>
